# Generated by Django 2.2.4 on 2019-09-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190908_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='avatar.svg', upload_to='profile_pics'),
        ),
    ]
